from datetime import datetime

from django.contrib.auth.models import User
from django.db import models

# Create your models here.
SURAHS = [
    ("The Opening", "Al-Faatiha"),
    ("The Cow", "Al-Baqara"),
    ("The Family of Imraan", "Aal-i-Imraan"),
    ("The Women", "An-Nisaa"),
    ("The Table", "Al-Maaida"),
    ("The Cattle", "Al-An'aam"),
    ("The Heights", "Al-A'raaf"),
    ("The Spoils of War", "Al-Anfaal"),
    ("The Repentance", "At-Tawba"),
    ("Jonas", "Yunus"),
    ("Hud", "Hud"),
    ("Joseph", "Yusuf"),
    ("The Thunder", "Ar-Ra'd"),
    ("Abraham", "Ibrahim"),
    ("The Rock", "Al-Hijr"),
    ("The Bee", "An-Nahl"),
    ("The Night Journey", "Al-Israa"),
    ("The Cave", "Al-Kahf"),
    ("Mary", "Maryam"),
    ("Taa-Haa", "Taa-Haa"),
    ("The Prophets", "Al-Anbiyaa"),
    ("The Pilgrimage", "Al-Hajj"),
    ("The Believers", "Al-Muminoon"),
    ("The Light", "An-Noor"),
    ("The Criterion", "Al-Furqaan"),
    ("The Poets", "Ash-Shu'araa"),
    ("The Ant", "An-Naml"),
    ("The Stories", "Al-Qasas"),
    ("The Spider", "Al-Ankaboot"),
    ("The Romans", "Ar-Room"),
    ("Luqman", "Luqman"),
    ("The Prostration", "As-Sajda"),
    ("The Clans", "Al-Ahzaab"),
    ("Sheba", "Saba"),
    ("The Originator", "Faatir"),
    ("Yaseen", "Yaseen"),
    ("Those drawn up in Ranks", "As-Saaffaat"),
    ("The letter Saad", "Saad"),
    ("The Groups", "Az-Zumar"),
    ("The Forgiver", "Ghafir"),
    ("Explained in detail", "Fussilat"),
    ("Consultation", "Ash-Shura"),
    ("Ornaments of gold", "Az-Zukhruf"),
    ("The Smoke", "Ad-Dukhaan"),
    ("Crouching", "Al-Jaathiya"),
    ("The Dunes", "Al-Ahqaf"),
    ("Muhammad", "Muhammad"),
    ("The Victory", "Al-Fath"),
    ("The Inner Apartments", "Al-Hujuraat"),
    ("The letter Qaaf", "Qaaf"),
    ("The Winnowing Winds", "Adh-Dhaariyat"),
    ("The Mount", "At-Tur"),
    ("The Star", "An-Najm"),
    ("The Moon", "Al-Qamar"),
    ("The Beneficent", "Ar-Rahmaan"),
    ("The Inevitable", "Al-Waaqia"),
    ("The Iron", "Al-Hadid"),
    ("The Pleading Woman", "Al-Mujaadila"),
    ("The Exile", "Al-Hashr"),
    ("She that is to be examined", "Al-Mumtahana"),
    ("The Ranks", "As-Saff"),
    ("Friday", "Al-Jumu'a"),
    ("The Hypocrites", "Al-Munaafiqoon"),
    ("Mutual Disillusion", "At-Taghaabun"),
    ("Divorce", "At-Talaaq"),
    ("The Prohibition", "At-Tahrim"),
    ("The Sovereignty", "Al-Mulk"),
    ("The Pen", "Al-Qalam"),
    ("The Reality", "Al-Haaqqa"),
    ("The Ascending Stairways", "Al-Ma'aarij"),
    ("Noah", "Nooh"),
    ("The Jinn", "Al-Jinn"),
    ("The Enshrouded One", "Al-Muzzammil"),
    ("The Cloaked One", "Al-Muddaththir"),
    ("The Resurrection", "Al-Qiyaama"),
    ("Man", "Al-Insaan"),
    ("The Emissaries", "Al-Mursalaat"),
    ("The Announcement", "An-Naba"),
    ("Those who drag forth", "An-Naazi'aat"),
    ("He frowned", "Abasa"),
    ("The Overthrowing", "At-Takwir"),
    ("The Cleaving", "Al-Infitaar"),
    ("Defrauding", "Al-Mutaffifin"),
    ("The Splitting Open", "Al-Inshiqaaq"),
    ("The Constellations", "Al-Burooj"),
    ("The Morning Star", "At-Taariq"),
    ("The Most High", "Al-A'laa"),
    ("The Overwhelming", "Al-Ghaashiya"),
    ("The Dawn", "Al-Fajr"),
    ("The City", "Al-Balad"),
    ("The Sun", "Ash-Shams"),
    ("The Night", "Al-Lail"),
    ("The Morning Hours", "Ad-Dhuhaa"),
    ("The Consolation", "Ash-Sharh"),
    ("The Fig", "At-Tin"),
    ("The Clot", "Al-Alaq"),
    ("The Power, Fate", "Al-Qadr"),
    ("The Evidence", "Al-Bayyina"),
    ("The Earthquake", "Az-Zalzala"),
    ("The Chargers", "Al-Aadiyaat"),
    ("The Calamity", "Al-Qaari'a"),
    ("Competition", "At-Takaathur"),
    ("The Declining Day, Epoch", "Al-Asr"),
    ("The Traducer", "Al-Humaza"),
    ("The Elephant", "Al-Fil"),
    ("Quraysh", "Quraish"),
    ("Almsgiving", "Al-Maa'un"),
    ("Abundance", "Al-Kawthar"),
    ("The Disbelievers", "Al-Kaafiroon"),
    ("Divine Support", "An-Nasr"),
    ("The Palm Fibre", "Al-Masad"),
    ("Sincerity", "Al-Ikhlaas"),
    ("The Dawn", "Al-Falaq"),
    ("Mankind", "An-Naas"),
]


class Hafalan(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="hafalan")
    surat = models.CharField(max_length=75, choices=SURAHS)
    ayat_start = models.IntegerField(default=0)
    ayat_end = models.IntegerField(default=1)
    date = models.DateTimeField(blank=False, null=False, default=datetime.now())

    def get_full_name(self):
        return f"{self.user.first_name} {self.user.last_name}"

    def total_ayat(self):
        return self.ayat_end - self.ayat_start + 1

    def __str__(self):
        return f"{self.user.first_name} {self.user.last_name} ------------> {self.surat} : {self.ayat_start} - {self.ayat_end}"
