# Generated by Django 5.1.4 on 2024-12-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0003_rename_name_user_full_name_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(default='mahasiswa', max_length=75),
        ),
    ]
