# Generated by Django 5.1.4 on 2024-12-29 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0004_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('mahasiswa', 'Mahasiswa'), ('muhaffidz', 'Muhaffidz')], default='mahasiswa', max_length=75),
        ),
    ]
