# Generated by Django 5.1.4 on 2024-12-29 04:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0006_alter_hafalan_user_delete_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hafalan',
            name='ayat',
        ),
        migrations.AddField(
            model_name='hafalan',
            name='ayat_end',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='hafalan',
            name='ayat_start',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='hafalan',
            name='date',
            field=models.DateField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='hafalan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hafalan', to=settings.AUTH_USER_MODEL),
        ),
    ]
