# Generated by Django 5.1.4 on 2024-12-29 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0008_alter_hafalan_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hafalan',
            name='date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
