# Generated by Django 5.1.4 on 2025-01-02 12:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0013_alter_hafalan_date_alter_hafalan_surat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hafalan',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 2, 19, 44, 27, 41538)),
        ),
        migrations.AlterField(
            model_name='hafalan',
            name='surat',
            field=models.CharField(choices=[('The Opening', 'Al-Faatiha'), ('The Cow', 'Al-Baqara'), ('The Family of Imraan', 'Aal-i-Imraan'), ('The Women', 'An-Nisaa'), ('The Table', 'Al-Maaida'), ('The Cattle', "Al-An'aam"), ('The Heights', "Al-A'raaf"), ('The Spoils of War', 'Al-Anfaal'), ('The Repentance', 'At-Tawba'), ('Jonas', 'Yunus'), ('Hud', 'Hud'), ('Joseph', 'Yusuf'), ('The Thunder', "Ar-Ra'd"), ('Abraham', 'Ibrahim'), ('The Rock', 'Al-Hijr'), ('The Bee', 'An-Nahl'), ('The Night Journey', 'Al-Israa'), ('The Cave', 'Al-Kahf'), ('Mary', 'Maryam'), ('Taa-Haa', 'Taa-Haa'), ('The Prophets', 'Al-Anbiyaa'), ('The Pilgrimage', 'Al-Hajj'), ('The Believers', 'Al-Muminoon'), ('The Light', 'An-Noor'), ('The Criterion', 'Al-Furqaan'), ('The Poets', "Ash-Shu'araa"), ('The Ant', 'An-Naml'), ('The Stories', 'Al-Qasas'), ('The Spider', 'Al-Ankaboot'), ('The Romans', 'Ar-Room'), ('Luqman', 'Luqman'), ('The Prostration', 'As-Sajda'), ('The Clans', 'Al-Ahzaab'), ('Sheba', 'Saba'), ('The Originator', 'Faatir'), ('Yaseen', 'Yaseen'), ('Those drawn up in Ranks', 'As-Saaffaat'), ('The letter Saad', 'Saad'), ('The Groups', 'Az-Zumar'), ('The Forgiver', 'Ghafir'), ('Explained in detail', 'Fussilat'), ('Consultation', 'Ash-Shura'), ('Ornaments of gold', 'Az-Zukhruf'), ('The Smoke', 'Ad-Dukhaan'), ('Crouching', 'Al-Jaathiya'), ('The Dunes', 'Al-Ahqaf'), ('Muhammad', 'Muhammad'), ('The Victory', 'Al-Fath'), ('The Inner Apartments', 'Al-Hujuraat'), ('The letter Qaaf', 'Qaaf'), ('The Winnowing Winds', 'Adh-Dhaariyat'), ('The Mount', 'At-Tur'), ('The Star', 'An-Najm'), ('The Moon', 'Al-Qamar'), ('The Beneficent', 'Ar-Rahmaan'), ('The Inevitable', 'Al-Waaqia'), ('The Iron', 'Al-Hadid'), ('The Pleading Woman', 'Al-Mujaadila'), ('The Exile', 'Al-Hashr'), ('She that is to be examined', 'Al-Mumtahana'), ('The Ranks', 'As-Saff'), ('Friday', "Al-Jumu'a"), ('The Hypocrites', 'Al-Munaafiqoon'), ('Mutual Disillusion', 'At-Taghaabun'), ('Divorce', 'At-Talaaq'), ('The Prohibition', 'At-Tahrim'), ('The Sovereignty', 'Al-Mulk'), ('The Pen', 'Al-Qalam'), ('The Reality', 'Al-Haaqqa'), ('The Ascending Stairways', "Al-Ma'aarij"), ('Noah', 'Nooh'), ('The Jinn', 'Al-Jinn'), ('The Enshrouded One', 'Al-Muzzammil'), ('The Cloaked One', 'Al-Muddaththir'), ('The Resurrection', 'Al-Qiyaama'), ('Man', 'Al-Insaan'), ('The Emissaries', 'Al-Mursalaat'), ('The Announcement', 'An-Naba'), ('Those who drag forth', "An-Naazi'aat"), ('He frowned', 'Abasa'), ('The Overthrowing', 'At-Takwir'), ('The Cleaving', 'Al-Infitaar'), ('Defrauding', 'Al-Mutaffifin'), ('The Splitting Open', 'Al-Inshiqaaq'), ('The Constellations', 'Al-Burooj'), ('The Morning Star', 'At-Taariq'), ('The Most High', "Al-A'laa"), ('The Overwhelming', 'Al-Ghaashiya'), ('The Dawn', 'Al-Fajr'), ('The City', 'Al-Balad'), ('The Sun', 'Ash-Shams'), ('The Night', 'Al-Lail'), ('The Morning Hours', 'Ad-Dhuhaa'), ('The Consolation', 'Ash-Sharh'), ('The Fig', 'At-Tin'), ('The Clot', 'Al-Alaq'), ('The Power, Fate', 'Al-Qadr'), ('The Evidence', 'Al-Bayyina'), ('The Earthquake', 'Az-Zalzala'), ('The Chargers', 'Al-Aadiyaat'), ('The Calamity', "Al-Qaari'a"), ('Competition', 'At-Takaathur'), ('The Declining Day, Epoch', 'Al-Asr'), ('The Traducer', 'Al-Humaza'), ('The Elephant', 'Al-Fil'), ('Quraysh', 'Quraish'), ('Almsgiving', "Al-Maa'un"), ('Abundance', 'Al-Kawthar'), ('The Disbelievers', 'Al-Kaafiroon'), ('Divine Support', 'An-Nasr'), ('The Palm Fibre', 'Al-Masad'), ('Sincerity', 'Al-Ikhlaas'), ('The Dawn', 'Al-Falaq'), ('Mankind', 'An-Naas')], max_length=75),
        ),
    ]
