# Generated by Django 5.1.4 on 2025-01-03 08:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0014_alter_hafalan_date_alter_hafalan_surat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hafalan',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 3, 15, 28, 9, 481428)),
        ),
        migrations.AlterField(
            model_name='hafalan',
            name='surat',
            field=models.CharField(choices=[('Al-Faatiha', 'Al-Faatiha'), ('Al-Baqara', 'Al-Baqara'), ('Aal-i-Imraan', 'Aal-i-Imraan'), ('An-Nisaa', 'An-Nisaa'), ('Al-Maaida', 'Al-Maaida'), ("Al-An'aam", "Al-An'aam"), ("Al-A'raaf", "Al-A'raaf"), ('Al-Anfaal', 'Al-Anfaal'), ('At-Tawba', 'At-Tawba'), ('Yunus', 'Yunus'), ('Hud', 'Hud'), ('Yusuf', 'Yusuf'), ("Ar-Ra'd", "Ar-Ra'd"), ('Ibrahim', 'Ibrahim'), ('Al-Hijr', 'Al-Hijr'), ('An-Nahl', 'An-Nahl'), ('Al-Israa', 'Al-Israa'), ('Al-Kahf', 'Al-Kahf'), ('Maryam', 'Maryam'), ('Taa-Haa', 'Taa-Haa'), ('Al-Anbiyaa', 'Al-Anbiyaa'), ('Al-Hajj', 'Al-Hajj'), ('Al-Muminoon', 'Al-Muminoon'), ('An-Noor', 'An-Noor'), ('Al-Furqaan', 'Al-Furqaan'), ("Ash-Shu'araa", "Ash-Shu'araa"), ('An-Naml', 'An-Naml'), ('Al-Qasas', 'Al-Qasas'), ('Al-Ankaboot', 'Al-Ankaboot'), ('Ar-Room', 'Ar-Room'), ('Luqman', 'Luqman'), ('As-Sajda', 'As-Sajda'), ('Al-Ahzaab', 'Al-Ahzaab'), ('Saba', 'Saba'), ('Faatir', 'Faatir'), ('Yaseen', 'Yaseen'), ('As-Saaffaat', 'As-Saaffaat'), ('Saad', 'Saad'), ('Az-Zumar', 'Az-Zumar'), ('Ghafir', 'Ghafir'), ('Fussilat', 'Fussilat'), ('Ash-Shura', 'Ash-Shura'), ('Az-Zukhruf', 'Az-Zukhruf'), ('Ad-Dukhaan', 'Ad-Dukhaan'), ('Al-Jaathiya', 'Al-Jaathiya'), ('Al-Ahqaf', 'Al-Ahqaf'), ('Muhammad', 'Muhammad'), ('Al-Fath', 'Al-Fath'), ('Al-Hujuraat', 'Al-Hujuraat'), ('Qaaf', 'Qaaf'), ('Adh-Dhaariyat', 'Adh-Dhaariyat'), ('At-Tur', 'At-Tur'), ('An-Najm', 'An-Najm'), ('Al-Qamar', 'Al-Qamar'), ('Ar-Rahmaan', 'Ar-Rahmaan'), ('Al-Waaqia', 'Al-Waaqia'), ('Al-Hadid', 'Al-Hadid'), ('Al-Mujaadila', 'Al-Mujaadila'), ('Al-Hashr', 'Al-Hashr'), ('Al-Mumtahana', 'Al-Mumtahana'), ('As-Saff', 'As-Saff'), ("Al-Jumu'a", "Al-Jumu'a"), ('Al-Munaafiqoon', 'Al-Munaafiqoon'), ('At-Taghaabun', 'At-Taghaabun'), ('At-Talaaq', 'At-Talaaq'), ('At-Tahrim', 'At-Tahrim'), ('Al-Mulk', 'Al-Mulk'), ('Al-Qalam', 'Al-Qalam'), ('Al-Haaqqa', 'Al-Haaqqa'), ("Al-Ma'aarij", "Al-Ma'aarij"), ('Nooh', 'Nooh'), ('Al-Jinn', 'Al-Jinn'), ('Al-Muzzammil', 'Al-Muzzammil'), ('Al-Muddaththir', 'Al-Muddaththir'), ('Al-Qiyaama', 'Al-Qiyaama'), ('Al-Insaan', 'Al-Insaan'), ('Al-Mursalaat', 'Al-Mursalaat'), ('An-Naba', 'An-Naba'), ("An-Naazi'aat", "An-Naazi'aat"), ('Abasa', 'Abasa'), ('At-Takwir', 'At-Takwir'), ('Al-Infitaar', 'Al-Infitaar'), ('Al-Mutaffifin', 'Al-Mutaffifin'), ('Al-Inshiqaaq', 'Al-Inshiqaaq'), ('Al-Burooj', 'Al-Burooj'), ('At-Taariq', 'At-Taariq'), ("Al-A'laa", "Al-A'laa"), ('Al-Ghaashiya', 'Al-Ghaashiya'), ('Al-Fajr', 'Al-Fajr'), ('Al-Balad', 'Al-Balad'), ('Ash-Shams', 'Ash-Shams'), ('Al-Lail', 'Al-Lail'), ('Ad-Dhuhaa', 'Ad-Dhuhaa'), ('Ash-Sharh', 'Ash-Sharh'), ('At-Tin', 'At-Tin'), ('Al-Alaq', 'Al-Alaq'), ('Al-Qadr', 'Al-Qadr'), ('Al-Bayyina', 'Al-Bayyina'), ('Az-Zalzala', 'Az-Zalzala'), ('Al-Aadiyaat', 'Al-Aadiyaat'), ("Al-Qaari'a", "Al-Qaari'a"), ('At-Takaathur', 'At-Takaathur'), ('Al-Asr', 'Al-Asr'), ('Al-Humaza', 'Al-Humaza'), ('Al-Fil', 'Al-Fil'), ('Quraish', 'Quraish'), ("Al-Maa'un", "Al-Maa'un"), ('Al-Kawthar', 'Al-Kawthar'), ('Al-Kaafiroon', 'Al-Kaafiroon'), ('An-Nasr', 'An-Nasr'), ('Al-Masad', 'Al-Masad'), ('Al-Ikhlaas', 'Al-Ikhlaas'), ('Al-Falaq', 'Al-Falaq'), ('An-Naas', 'An-Naas')], max_length=75),
        ),
    ]
