# Generated by Django 5.1.4 on 2025-01-04 16:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0030_alter_hafalan_date_passwordresettoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hafalan',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 4, 23, 44, 57, 684011)),
        ),
    ]
