# Generated by Django 5.1.4 on 2025-01-04 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0032_alter_hafalan_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hafalan',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 0, 8, 46, 318456)),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 0, 8, 46, 318727)),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 0, 38, 46, 318737)),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='a434d4099d0a794460aacfe5b4b20576096fe4bbdfc87a2c9ad54f2141de6e3e', max_length=64, unique=True),
        ),
    ]
