# Generated by Django 5.1.4 on 2025-01-05 02:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0033_alter_hafalan_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hafalan',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 9, 56, 57, 800042)),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 9, 56, 57, 800316)),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 5, 10, 26, 57, 800326)),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='e6afea3f658dfc670154ec47055b13114fa7fdcf755db75ddd82db992cab01bb', max_length=64, unique=True),
        ),
    ]
