# Generated by Django 5.1.4 on 2025-01-06 15:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0034_alter_hafalan_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hafalan',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 22, 16, 15, 510486)),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 22, 16, 15, 510748)),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 22, 46, 15, 510757)),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='6f20296a43a7c1ddf710548e1ebfc1468fcd18d1981267324074eb044c727e8d', max_length=64, unique=True),
        ),
    ]
