# Generated by Django 5.1.4 on 2025-01-06 15:31

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_site', '0035_alter_hafalan_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hafalan',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 22, 31, 25, 835039)),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 22, 31, 25, 835305)),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='expires_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 1, 6, 23, 1, 25, 835314)),
        ),
        migrations.AlterField(
            model_name='passwordresettoken',
            name='token',
            field=models.CharField(default='b9368bae84f975ef23101b09283bdbcad737222556d6c0d25d1b866a2d9ca473', max_length=64, unique=True),
        ),
    ]
